language: ruby
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - 2.6

before_install:
  - "travis_retry gem update --system 2.7.9"
  - "travis_retry gem install bundler -v '1.17.3'"
install: BUNDLER_VERSION=1.17.3 bundle install --path=vendor/bundle --retry=3 --jobs=3

script:
  - bundle exec rspec
